2023-02-23 01:19:03,976 | root - WARNING - Bot started!
2023-02-23 01:19:06,853 | asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=TypeError("cmd_start() missing 1 required positional argument: 'dao'")>
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
TypeError: cmd_start() missing 1 required positional argument: 'dao'
2023-02-23 01:20:46,635 | asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=TypeError("cmd_start() missing 1 required positional argument: 'dao'")>
Traceback (most recent call last):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\zolin\University\API\miniLabs\2 semester\Todolist_Telegram_bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
TypeError: cmd_start() missing 1 required positional argument: 'dao'
2023-02-23 01:21:10,217 | aiogram.dispatcher.dispatcher - WARNING - Polling is stopped.
2023-02-23 01:21:10,219 | root - WARNING - Bot stopped!
